# Generated by Django 4.1.5 on 2023-01-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('page_views', models.IntegerField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.page')),
            ],
        ),
        migrations.CreateModel(
            name='ContentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=25)),
                ('content_views', models.IntegerField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.page')),
            ],
        ),
    ]
